# PREPROCESSING

In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = r"C:\Users\sneha\SupplyChainForecasting\data\raw\train (1).parquet"

df = pd.read_parquet(file_path)

print("Shape:", df.shape)
df.head()

Shape: (7869549, 19)

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,activity_flag,discount,holiday_flag,precpt,avg_temperature,avg_humidity,avg_wind_level
0,0,0,2,25,62,31,54,2025-04-30,0.9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.2, ...",5,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,0,1.4621,20.88,56.32,1.39
1,0,0,2,25,62,31,54,2025-05-01,2.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0,1.0,1,1.2773,21.52,57.65,1.63
2,0,0,2,25,62,31,54,2025-05-02,0.9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",7,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,1,1.1190,21.88,60.03,1.77
3,0,0,2,25,62,31,54,2025-05-03,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.2, ...",0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,1,1.8706,22.63,61.44,2.32
4,0,0,2,25,62,31,54,2025-05-04,1.2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0,1.0,1,2.1437,21.99,67.06,2.25

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 7869549 entries, 0 to 7869548
Data columns (total 19 columns):
 #   Column               Dtype
---  ------               -----
 0   city_id              int64
 1   store_id             int64
 2   management_group_id  int64
 3   first_category_id    int64
 4   second_category_id   int64
 5   third_category_id    int64
 6   product_id           int64
 7   dt                   str
 8   sale_amount          float64
 9   hours_sale           object
 10  stock_hour6_22_cnt   int32
 11  hours_stock_status   object
 12  activity_flag        int32
 13  discount             float64
 14  holiday_flag         int32
 15  precpt               float64
 16  avg_temperature      float64
 17  avg_humidity         float64
 18  avg_wind_level       float64
dtypes: float64(6), int32(3), int64(7), object(2), str(1)
memory usage: 1.1+ GB
None

### MISSING VALUES

In [5]:
missing = df.isnull().sum().to_frame("missing_count")

missing["missing_pct"] = (missing["missing_count"] / len(df) * 100)

print(missing[missing["missing_count"] > 0])

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

### DUPLICATE VALUES

In [6]:
#duplicate_cnt = df.duplicated().sum()
#print("Duplicate Count:", duplicate_cnt) 
#  // can't run this since there are 2 columns which are of obj dtype and have unhashable types (list) in them. So, can't check for duplicates.

In [7]:
for col in df.columns:
    if df[col].dtype == "object":
        print(f"\n{col}")
        print(df[col].head(5).apply(type).value_counts())

hours_sale
hours_sale
<class 'numpy.ndarray'>    5
Name: count, dtype: int64

hours_stock_status
hours_stock_status
<class 'numpy.ndarray'>    5
Name: count, dtype: int64

In [8]:
print("hours_sale:")
print(df["hours_sale"].iloc[0])
print(type(df["hours_sale"].iloc[0]))

print("\nhours_stock_status:")
print(df["hours_stock_status"].iloc[0])
print(type(df["hours_stock_status"].iloc[0]))

hours_sale:
[0.  0.  0.  0.  0.  0.  0.1 0.  0.2 0.1 0.  0.1 0.1 0.  0.1 0.  0.2 0.
 0.  0.  0.  0.  0.  0. ]
<class 'numpy.ndarray'>

hours_stock_status:
[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
<class 'numpy.ndarray'>

In [9]:
print("hours_sale shape:", df["hours_sale"].iloc[0].shape)
print("hours_stock_status shape:", df["hours_stock_status"].iloc[0].shape)

print(df["hours_sale"].apply(len).value_counts())

print( df["hours_stock_status"].apply(len).value_counts())

hours_sale shape: (24,)
hours_stock_status shape: (24,)
hours_sale
24    7869549
Name: count, dtype: int64
hours_stock_status
24    7869549
Name: count, dtype: int64

In [10]:
normal_cols = [
    col for col in df.columns
    if col not in ["hours_sale", "hours_stock_status"]
]

duplicate_cnt = df[normal_cols].duplicated().sum()

print("Duplicate count (excluding hourly arrays):", duplicate_cnt)

Duplicate count (excluding hourly arrays): 0

### DATA TYPES

In [11]:
print(df.dtypes)

city_id                  int64
store_id                 int64
management_group_id      int64
first_category_id        int64
second_category_id       int64
third_category_id        int64
product_id               int64
dt                         str
sale_amount            float64
hours_sale              object
stock_hour6_22_cnt       int32
hours_stock_status      object
activity_flag            int32
discount               float64
holiday_flag             int32
precpt                 float64
avg_temperature        float64
avg_humidity           float64
avg_wind_level         float64
dtype: object

In [12]:
df['dt']=pd.to_datetime(df['dt'])

In [13]:
print(df['dt'].dtype)

datetime64[us]

### INVALID VALUES

In [14]:
#CHECK FOR -VE SALE AMOUNT  
print("Minimum sale_amount:", df["sale_amount"].min())
print("Maximum sale_amount:", df["sale_amount"].max())

Minimum sale_amount: 0.0
Maximum sale_amount: 83.7

In [15]:

print("Minimum discount:", df["discount"].min())
print("Maximum discount:", df["discount"].max())

Minimum discount: 0.3
Maximum discount: 1.0

In [16]:
print("Minimum stockout hours:", df["stock_hour6_22_cnt"].min())
print("Maximum stockout hours:", df["stock_hour6_22_cnt"].max())

Minimum stockout hours: 0
Maximum stockout hours: 16

In [17]:
print("activity_flag:", df["activity_flag"].unique())
print("holiday_flag:", df["holiday_flag"].unique())

activity_flag: [0 1]
holiday_flag: [0 1]

# FEATURE ENGINEERING

### DATE FEATURES

In [18]:
df["year"]=df["dt"].dt.year
df["month"]=df["dt"].dt.month
df["day_of_month"] = df["dt"].dt.day
df["day_of_week"] = df["dt"].dt.dayofweek
df["week_of_year"] = df["dt"].dt.isocalendar().week.astype("int8")
df["quarter"] = df["dt"].dt.quarter
df["is_weekend"] = (df["day_of_week"] >= 5).astype("int8")
df[["dt","year","month","day_of_month","day_of_week","week_of_year","quarter","is_weekend"]].head()

,dt,year,month,day_of_month,day_of_week,week_of_year,quarter,is_weekend
0,2025-04-30,2025,4,30,2,18,2,0
1,2025-05-01,2025,5,1,3,18,2,0
2,2025-05-02,2025,5,2,4,18,2,0
3,2025-05-03,2025,5,3,5,18,2,1
4,2025-05-04,2025,5,4,6,18,2,1

### LAG FEATURES

In [19]:
# Check how many unique dates each store-product combination has
date_counts = (df.groupby(["store_id", "product_id"])["dt"].nunique())

print(date_counts.describe())

count    22939.000000
mean       343.064170
std        256.783197
min         42.000000
25%        112.000000
50%        236.000000
75%        607.000000
max        770.000000
Name: dt, dtype: float64

In [20]:
date_gaps = (
    df.sort_values(["store_id", "product_id", "dt"])
      .groupby(["store_id", "product_id"])["dt"]
      .diff()
      .dt.days
)

print(date_gaps.value_counts().sort_index().head(20))

dt
1.0     7834109
2.0         582
3.0         327
4.0         200
5.0         191
6.0         128
7.0          75
8.0          42
9.0         174
10.0        143
11.0        155
12.0         79
13.0        109
14.0        121
15.0         72
16.0        161
17.0        212
18.0         53
19.0         65
20.0         46
Name: count, dtype: int64

In [21]:
lag_days = [1, 7, 14, 28]

for lag in lag_days:
    lag_df = df[["store_id", "product_id", "dt", "sale_amount"]].copy()
    lag_df["dt"] = lag_df["dt"] + pd.Timedelta(days=lag)

    df = df.merge(
        lag_df,
        on=["store_id", "product_id", "dt"],
        how="left",
        suffixes=("", f"_lag_{lag}")
    )

    df.rename(
        columns={"sale_amount_lag_" + str(lag): f"lag_{lag}"},
        inplace=True
    )

In [22]:
df[[ "store_id","product_id","dt","sale_amount","lag_1","lag_7","lag_14","lag_28"]].head(15)

    store_id  product_id         dt  sale_amount  lag_1  lag_7  lag_14  lag_28
0          0          54 2025-04-30          0.9    NaN    NaN     NaN     NaN
1          0          54 2025-05-01          2.0    0.9    NaN     NaN     NaN
2          0          54 2025-05-02          0.9    2.0    NaN     NaN     NaN
3          0          54 2025-05-03          1.0    0.9    NaN     NaN     NaN
4          0          54 2025-05-04          1.2    1.0    NaN     NaN     NaN
5          0          54 2025-05-05          1.3    1.2    NaN     NaN     NaN
6          0          54 2025-05-06          0.7    1.3    NaN     NaN     NaN
7          0          54 2025-05-07          1.2    0.7    0.9     NaN     NaN
8          0          54 2025-05-08          1.5    1.2    2.0     NaN     NaN
9          0          54 2025-05-09          1.4    1.5    0.9     NaN     NaN
10         0          54 2025-05-10          1.7    1.4    1.0     NaN     NaN
11         0          54 2025-05-11          1.8    1.7    1.2     NaN     NaN
12         0          54 2025-05-12          1.0    1.8    1.3     NaN     NaN
13         0          54 2025-05-13          0.5    1.0    0.7     NaN     NaN
14         0          54 2025-05-14          1.1    0.5    1.2     0.9     NaN

In [23]:
df["sales_shifted"] = (df.groupby(["store_id", "product_id"])["sale_amount"].shift(1))

In [24]:
for window in [7, 14, 28]:
    df[f"rolling_mean_{window}"] = (
        df.groupby(["store_id", "product_id"])["sales_shifted"]
          .transform(lambda x: x.rolling(window).mean())
    )

In [25]:
df[["store_id","product_id","dt","sale_amount","sales_shifted","rolling_mean_7","rolling_mean_14","rolling_mean_28"]].head(15)

,store_id,product_id,dt,sale_amount,sales_shifted,rolling_mean_7,rolling_mean_14,rolling_mean_28
0,0,54,2025-04-30,0.9,NaN,NaN,NaN,NaN
1,0,54,2025-05-01,2.0,0.9,NaN,NaN,NaN
2,0,54,2025-05-02,0.9,2.0,NaN,NaN,NaN
3,0,54,2025-05-03,1.0,0.9,NaN,NaN,NaN
4,0,54,2025-05-04,1.2,1.0,NaN,NaN,NaN
5,0,54,2025-05-05,1.3,1.2,NaN,NaN,NaN
6,0,54,2025-05-06,0.7,1.3,NaN,NaN,NaN
7,0,54,2025-05-07,1.2,0.7,1.142857,NaN,NaN
8,0,54,2025-05-08,1.5,1.2,1.185714,NaN,NaN
9,0,54,2025-05-09,1.4,1.5,1.114286,NaN,NaN
10,0,54,2025-05-10,1.7,1.4,1.185714,NaN,NaN
11,0,54,2025-05-11,1.8,1.7,1.285714,NaN,NaN
12,0,54,2025-05-12,1.0,1.8,1.371429,NaN,NaN
13,0,54,2025-05-13,0.5,1.0,1.328571,NaN,NaN
14,0,54,2025-05-14,1.1,0.5,1.300000,1.221429,NaN

In [26]:
df.shape

(7869549, 34)

In [ ]:
df = df.drop(columns=["management_group_id","first_category_id","second_category_id","third_category_id"])

In [28]:
df.shape

(7869549, 30)

In [29]:
df.drop(columns=["sales_shifted"], inplace=True)
df.shape

(7869549, 29)

In [30]:
df.head()

,city_id,store_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,activity_flag,discount,...,week_of_year,quarter,is_weekend,lag_1,lag_7,lag_14,lag_28,rolling_mean_7,rolling_mean_14,rolling_mean_28
0,0,0,54,2025-04-30,0.9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.2, ...",5,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,...,18,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,54,2025-05-01,2.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0,1.0,...,18,2,0,0.9,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,54,2025-05-02,0.9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",7,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,...,18,2,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,54,2025-05-03,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.2, ...",0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1.0,...,18,2,1,0.9,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,54,2025-05-04,1.2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...",0,1.0,...,18,2,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
feature_cols = [
    "lag_1", "lag_7", "lag_14", "lag_28",
    "rolling_mean_7", "rolling_mean_14", "rolling_mean_28"
]

missing_features = df[feature_cols].isna().sum()

print(missing_features)

lag_1               35440
lag_7              237619
lag_14             467790
lag_28             891864
rolling_mean_7     160573
rolling_mean_14    321146
rolling_mean_28    642292
dtype: int64

In [32]:
print(df[feature_cols].isna().any(axis=1).sum())
print(df[feature_cols].isna().any(axis=1).mean() * 100)

915061
11.627870923734003

In [33]:
print(df.columns.tolist())

['city_id', 'store_id', 'product_id', 'dt', 'sale_amount', 'hours_sale', 'stock_hour6_22_cnt', 'hours_stock_status', 'activity_flag', 'discount', 'holiday_flag', 'precpt', 'avg_temperature', 'avg_humidity', 'avg_wind_level', 'year', 'month', 'day_of_month', 'day_of_week', 'week_of_year', 'quarter', 'is_weekend', 'lag_1', 'lag_7', 'lag_14', 'lag_28', 'rolling_mean_7', 'rolling_mean_14', 'rolling_mean_28']

In [34]:
print("Rows:", len(df))
print(
    "Duplicate store-product-date:",
    df.duplicated(["store_id", "product_id", "dt"]).sum()
)

Rows: 7869549
Duplicate store-product-date: 0

In [35]:
from pathlib import Path

Path("data/processed").mkdir(parents=True, exist_ok=True)

In [36]:
save_cols = [
    col for col in df.columns
    if col not in ["hours_sale", "hours_stock_status"]
]

df_fe = df[save_cols].copy()

df_fe.to_parquet("../data/processed/sales_feature_engineered.parquet",index=False)

In [37]:
df_fe

,city_id,store_id,product_id,dt,sale_amount,stock_hour6_22_cnt,activity_flag,discount,holiday_flag,precpt,...,week_of_year,quarter,is_weekend,lag_1,lag_7,lag_14,lag_28,rolling_mean_7,rolling_mean_14,rolling_mean_28
0,0,0,54,2025-04-30,0.9,5,0,1.0,0,1.4621,...,18,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,0,54,2025-05-01,2.0,10,0,1.0,1,1.2773,...,18,2,0,0.9,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,54,2025-05-02,0.9,7,0,1.0,1,1.1190,...,18,2,0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,0,0,54,2025-05-03,1.0,0,0,1.0,1,1.8706,...,18,2,1,0.9,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,54,2025-05-04,1.2,9,0,1.0,1,2.1437,...,18,2,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7869544,17,1056,407,2023-10-19,0.0,16,0,1.0,0,0.4327,...,42,4,0,4.0,0.0,0.0,8.3,3.928571,5.000000,5.957143
7869545,17,1056,407,2023-10-20,0.0,16,0,1.0,0,0.3602,...,42,4,0,0.0,0.0,8.4,7.9,3.928571,5.000000,5.660714
7869546,17,1056,407,2023-10-21,0.0,16,0,1.0,1,0.2060,...,42,4,1,0.0,9.4,9.0,7.6,3.928571,4.400000,5.378571
7869547,17,1056,407,2023-10-22,0.0,16,0,1.0,1,0.0000,...,42,4,1,0.0,5.5,8.5,8.4,2.585714,3.757143,5.107143
7869548,17,1056,407,2023-10-23,0.0,16,0,1.0,0,0.0000,...,43,4,0,0.0,3.6,0.0,8.1,1.800000,3.150000,4.807143

In [39]:
df_fe.head(100).to_csv("../data/processed/sales_feature_engineered_sample100.csv",index=False)